### ISSUE TITLE
Setting "expanded" property has no effect

### ISSUE THREAD

**Issue by gstroup** [predixdesignsystem/px-alert-message#41]
## Expected behavior and actual behavior:
If the message is long, I may want to default the px-alert-message to "expanded" mode.  This doesn't work as I expected.  I don't want my user to have to click "Show more".

## Steps to reproduce the problem:
Set `expanded` property in HTML or JS.  Set `message` to a long string.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Chrome 63 on Mac

## Code example

https://codepen.io/anon/pen/jYWjaN?&editors=1001

**Comment by randyaskin** [comment]
It works fine for me in Chrome Inspector if I either add the property to the HTML or use JS to change it. It seems to just be an initialization / timing problem that you can't code it into your HTML to start with - we'll look into it! Thanks Greg.

**Comment by randyaskin** [comment]
@davidrleonard I think you've touched this code most recently, any ideas? I think it may be because `_checkMessageLength` is turning `expanded` off, but if I comment that out, then `overset` never gets set correctly in the first place.

**Comment by arongraham-ge** [comment]
@gstroup release 1.3.4 now supports this behavior. If you add the **expanded** property to the <px-alert-message> then add it to the DOM it will open the message in "expanded" mode without the "Show More" link. Please let us know if you have any questions.
