### ISSUE TITLE
Line break at sentences' end in a single toast of px-alert-message

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-alert-message#42]
Hi,
in px-alert-message is there a way  to insert line break at the end of the sentence, when 2 sentences with a line break are passed a string to messageTitle property?
Currently it doesn't seem to read the new line in the string.
If i pass: 
'ABcsdf 
sdfk'
in message Title, it shows 'ABcsdf sdfk' itself is shown.
Is there a support in px-alert-message to break the string at full stop or read the newline break in message inserted in messageTitle property?
If not, is there going to be any provision in the future?
Need urgent help on this issue. Thanks in advance.

**Comment by nonmetalhail** [comment]
You can slot in custom html into the `content` slot to achieve what you want. See this demo for an example: https://github.com/predixdesignsystem/px-alert-message/blob/master/demo/demo.html
