### ISSUE TITLE
Specifying 2 different actions in the message

### ISSUE THREAD

**Issue by priyabrat1801** [predixdesignsystem/px-alert-message#46]
Hi,
We have requirement to show 2 different actions in the toast message e.g ok & cancel. Where one action will continue the state and the other will stop the state of the action. Could not find a way to support it with current implementation.

Also, would like to provide the text to the buttons as input to override the default texts.

Thanks,
Priyabrat

**Comment by evanjd** [comment]
The current design doesn't accomodate for multiple actions, so we'd need to check with the design team to work out how best to support your requirements.

Any chance your requirements could be served by px-modal?
<img width="420" alt="screen shot 2019-02-13 at 9 33 00 am" src="https://user-images.githubusercontent.com/4055224/52672588-62179280-2f72-11e9-9a4d-0ceadd00cb42.png">
```html
<px-modal
  header-text="Confirm <action>"
   body-text="Do you want to <action>?"
   accept-text="OK"
   reject-text="Cancel">
</px-modal>
```

**Comment by priyabrat1801** [comment]
@evanjd modal will work. However, we wanted to show it as a toast message and not block the interaction behind the modal. That where the requirement is from.

**Comment by evanjd** [comment]
Makes sense @priyabrat1801.

What about overriding the alert message content yourself? For example:

<img width="422" alt="screen shot 2019-02-13 at 10 22 41 am" src="https://user-images.githubusercontent.com/4055224/52674992-5ed3d500-2f79-11e9-943a-4dd8f1de183e.png">

```html
<px-alert-message type="information">
  <div slot="content">
    <span>Custom notification</span>
    <div style="float: right">
      <button class="btn btn--tertiary">Button 1</button>
      <button class="btn btn--tertiary">Button 2</button>
    </div>
  </div>
</px-alert-message>
```

Slapped together in a hurry, so I haven't imported [the button CSS module](https://www.predix-ui.com/#/css/visual/buttons/px-buttons-design) or styled the text properly, but you get the idea.

Glitch is here if interested: https://glitch.com/edit/#!/px-alert-message-custom-content?path=index.html:4:34

**Comment by priyabrat1801** [comment]
Thanks @evanjd. will try this option to see if this suffice our use case.
