### ISSUE TITLE
Fullscreen demo broken on predix-ui.com

### ISSUE THREAD

**Issue by MichaelZaporozhets** [predixdesignsystem/px-alert-message#47]
## Expected behavior and actual behavior:

https://www.predix-ui.com/#/elements/px-alert-message has a link to https://www.predix-ui.com/bower_components/px-alert-message/demo/demo.html which should show "Full-screen demo with several px-alert-messages in a queue." as per link title.

In reality, the linked page appears incomplete and upon inspecting the console, is ridden with errors.

## Steps to reproduce the problem:

open this link: https://www.predix-ui.com/bower_components/px-alert-message/demo/demo.html

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

## Screenshots (_optional, but very helpful_):

<img width="1677" alt="screen shot 2019-03-07 at 5 54 10 pm" src="https://user-images.githubusercontent.com/1571028/53937794-4aab6f80-4102-11e9-82d2-0ef076e44e48.png">

**Comment by evanjd** [comment]
I'd move this bug to [predix-ui](https://github.com/predix-ui/predix-ui.github.io). This is my bad, when I moved to site hosting to netlify I obviously broke this.
